url: https://www.henrikbecker.net
permalink: pretty

defaults:
 - scope:
    path: ""
   values: 
    layout: default      
    artist: Henrik Becker
    cover_url: /assets/img/folder.jpg
    library_url: https://henrikbecker.blob.core.windows.net/music
    license: 
     name: Creative Commons Attribution-NonCommercial-ShareAlike 4.0
     url: https://creativecommons.org/licenses/by-nc-sa/4.0/
 - scope:
    path: /albums/*
   values:      
    layout: album
    permalink: /:basename/index.html
 - scope:
    path: ""
    type: posts
   values:
    layout: song
    permalink: /:year/:day-:slug/index.html
     
sass:
 style: compressed

exclude:
 - node_modules
 - src
 - README.md
 - webpack.config.js
 - tsconfig.json
 - Gemfile*
 - package*
 - "*.orig"     